[package]
name    = "ht-dns"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes                = "1.5.0"
chacha20poly1305     = { version = "0.11.0-pre.2", features = ["stream"] }
mio                  = "0.8.11"
reed-solomon-erasure = "6.0.0"
socket2              = "0.5.8"
thiserror            = "1.0.61"
tokio                = { version = "1.43.0", features = ["full"] }
